### ISSUE TITLE
Failed preview publish without clear reason

### ISSUE THREAD

**Issue by taras** [thefrontside/playhouse#52]
We're getting failed preview publish steps.

It's not clear why this is happening

You can see it here https://github.com/thefrontside/backstage/runs/7288397238?check_suite_focus=true

<img width="988" alt="image" src="https://user-images.githubusercontent.com/74687/178361229-97a229bc-edb7-4797-b81c-02f67925c89c.png">

It fails here https://github.com/thefrontside/actions/blob/d5a4b48b6f3f3dc5daf7be88356a224bbee6de71/publish-pr-preview/src/publish.ts#L105

How can we get better feedback on why it's failing?

**Comment by cowboyd** [comment]
Looks like the invocation to `npm vetsion` Is failing with exit code 217. Is there an error map for npm?

otherwise, the result of `exec().expect()` is a `ProcessResult` and it has `stdout` and `stderr` as properties. 

https://frontside.com/effection/api/interfaces/_effection_process.Exec.html#expect

<blockquote><div><strong><a href="https://frontside.com/effection/api/interfaces/_effection_process.Exec.html#expect">Exec | Effection API Reference</a></strong></div><div>Documentation for Effection API Reference</div></blockquote>

**Comment by taras** [comment]
I did a bit of digging and I suspect that there is a problem with `exec().expect()`. It uses `process.expect()` which raises an `ExecError` when process fails. This makes it impossible to catch stdout or stderr from that process because even if you wrap the execution in a try catch, it never actually assign values to stdout and stderr.

```ts
    try {
      let { stdout, stderr } = yield exec(`npm version ${increaseFrom} --no-git-tag-version`, { cwd: directory }).expect();
      // when it throws, this is never reached so I can't actually read stdout/stderr
      console.log(`${stdout}`);
      console.log(`${stderr}`);
    } catch (e) {
      // here stdout/stderr are not available because they're never actually assigned
      console.error(`Error in publish ${e}`);
      throw e;
    }
```

**Comment by taras** [comment]
Fixed in `thefrontside/actions` repo
