### ISSUE TITLE
[GraphQL Plugin] Create sub-types based on the existing types

### ISSUE THREAD

**Issue by Blackbaud-LeoWanderer** [thefrontside/playhouse#75]
## Current behavior

I've got a few use cases where I need to query specific properties of a Components and Resources based on the `spec.type` or have the ability to _cast_ a type into a sub-type. For example, I've got a Pipeline resource like below:

```json
{
  "apiVersion": "backstage.io/v1beta1",
  "kind": "Resource",
  "metadata": {
    "namespace": "default",
    "name": "my-pipeline",
  },
  "spec": {
    "type": "pipeline",
    "pipelineId": 1234,
    "runState": "succeeded"
  }
}
```

and created a type in my gql schema for it: 

```graphql
type Pipeline @extend(type: "Entity") {
  runState: String! @field(at: "spec.runState")
}
```

Running the following query doesn't return the `runState` property, just returns the `name`.

```graphql
{
  entity(
    kind: "Resource"
    name: "my-pipeline"
  ) {
    name
    ... on Pipeline {
      runState
    }
  }
}
```

## Expected behavior

Have the ability to define sub-types so we can prevent the Resource and the Component types to get bloated with properties belonging to all their different sub-types.

**Comment by cowboyd** [comment]
Hmm.... maybe we can have a `descriminator` parameter to the `@extend()` directive in order to partition graphql types within a single entity kind:

```graphql
type Pipeline @extend(type: "Entity", discriminator: ["spec.type", "pipeline"]) {
#...
}
```

That said, I'm curious what is the tradeoff for actually having a separate entity kind of "Pipeline" rather than having a polymorphic spec object inside "Resource"?

**Comment by Blackbaud-LeoWanderer** [comment]
I see **resources** as physical entities in the cloud such as an "AWS S3 bucket", an "Azure Cosmos DB" or a "Kubernetes Cluster". Each of them will have properties inherent to the type (like the `storageType` - hot or cold - for an S3 bucket but not the others), and that's why I need the discrimination/inheritance/casting so I can avoid having 100s of props in the Resource gql type.

I understand the current resolver works based on the kind, and creating kinds will work but having 10s of kinds might become hard to maintain for me. I differentiate my "logical kinds" (components) from "physical kinds" (resources). For me, a component has several "instances" in different geo-zones, each of them is a cloud resource. This will unfortunately lead me to a path with too many kinds. In that sense, _casting_ a resource to a type will be the most convenient approach.

**Comment by cowboyd** [comment]
@Blackbaud-LeoWanderer I hear you. Data modeling is complex, and we want to make sure we have a system flexible enough to handle all the different different ways in which folks are using the catalog.

Maybe what we need is something like:

```graphql
type Pipeline @extend(type: "Resource", discriminator: ["spect.type", "pipeline"]) {
}
```

So since `Pipeline` extends `Resource` it automatically inherits its discriminators . The discriminator for `Resource` is `kind === "Resource"`, so the discriminator for `Pipeline` would be `kind === "Resource" && spec.type === "pipeline"`. Would that work?

**Comment by Blackbaud-LeoWanderer** [comment]
It makes sense and I believe it would work. @taras also mentioned this other approach on Discord: 
```(json)
type Pipeline @resolve(kind: "Resource" specType: "Pipeline") @extend(type: "Entity") { .... }
```
I don't have much experience with GQL to judge which of them will be best for extending the model in the future, but I'm happy to create a PR for whichever approach both of you believe will be best for the plugin.

**Comment by taras** [comment]
@Blackbaud-LeoWanderer it's the same idea but we can use the existing directive. That's better.

**Comment by wKich** [comment]
@Blackbaud-LeoWanderer That's a good idea and reasonable suggestion. Thank you.
@taras How about something like this?
`type Pipeline @resolve(by: "spec.type") extend(type: "Resource") { ... }`

**Comment by wKich** [comment]
@cowboyd btw we already tried to implement this `@extend(type: "Resource")` in our first PoC of the plugin. The main problem was, `Resource` should be an interface, not a type. But if you want to request resources, just common fields, we need to keep type and interface at the same time, but we can't because of name collision.

I think we can transform a type to an interface if we find using that type in `@extend` attribute. And we'll add a special type, like `UnkownResource` for any resources which we couldn't resolve.

**Comment by Blackbaud-LeoWanderer** [comment]
I had that same issue when I was trying to implement that functionality, that some types are concrete instead of interfaces.

I initially wanted to have the ability to do (un)boxing at query time, so that I would be able to get the same pipeline entity as `Pipeline` or as `Resource` depending on how the query was structured, but I couldn't figure out how to do it.

I did some experiments changing types to interfaces and was able to do what you're saying @wKich but I felt it was going to be a breaking change. Not sure if that's a feasible direction for you. 

Using `extend(..)` will make sense to me but I guess we need to add another parameter like the discriminator to the definition `type Pipeline @resolve(by: "spec.type") extend(type: "Resource") { ... }` since there could be multiple "types of resources".

**Comment by wKich** [comment]
> I initially wanted to have the ability to do (un)boxing at query time, so that I would be able to get the same pipeline entity as `Pipeline` or as `Resource` depending on how the query was structured, but I couldn't figure out how to do it.

I don't think it's possible. Inside resolvers you can resolve field values or their type according data, but you don't know what request query you got.

> Using `extend(..)` will make sense to me but I guess we need to add another parameter like the discriminator to the definition `type Pipeline @resolve(by: "spec.type") extend(type: "Resource") { ... }` since there could be multiple "types of resources".

You are right, that's why I suggested to add special type like `UnkownResource` or it might named `BaseResource`/`CommonResource` etc, so we can use `Resource` word as a name of the interface and don't have naming collisions. I think adding the discriminator is also adds complexity and opens ways to more complicated conditions. More over it doesn't solve naming collision issue, because we still need to use `Resource` as an interface name and a type for other resources.

Right now we resolve `Entity` type according `entity.kind` field, so think about it as like:
`type Resource extend(type: "Entity") { ... }` equals to `type Resource @resolve(by: "kind") extend(type: "Entity") { ... }`

**Comment by wKich** [comment]
@Blackbaud-LeoWanderer please correct me if I'm wrong, but I understand a way how the discriminator might be used, for example you have a resource entities which have `spec.type == "pipeline"`, and want to resolve them to `AzurePipeline` graphql type, not just `Pipeline`, so you'd like to have `type AzurePipeline @resolve(by: "spec.type",  discriminator: "pipeline") @extend(type: "Entity") { ... }`

It also allows define something like this:

*Allowed* 

* `type Website @extend(type: "Component" when: ["spec.type", "website"])`
* `type SillyWebsite @extend(type: "Website" when: ["spec.content", "silly"])`

*Not allowed*: 

* `type Website @extend(type: "Component" when: ["spec.type", "website"])`
* `type GoodWebsite @extend(type: "Component" when: ["spec.content", "good"])`
 
@cowboyd What do you think, is it worth it?

**Comment by Blackbaud-LeoWanderer** [comment]
I believe the discriminator adds a lot of flexibility and it can help in situations where the field has spaces, dashes or other characters too. I also like the ability to define `type Admin @resolve(by: "spec.login", discriminator: "admin@example.com") @extend(type: "User") { ... }`.
